# Generated by Django 3.2.3 on 2021-05-24 07:50

from django.db import migrations
import mainapp.utils


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210521_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=mainapp.utils.OrderField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=mainapp.utils.OrderField(blank=True, default='1'),
            preserve_default=False,
        ),
    ]
