# Generated by Django 3.2.5 on 2021-08-13 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='status',
            new_name='stat',
        ),
    ]
